CREATE PROCEDURE GetCandidates
AS
	IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Candidates'))
		EXEC CreateTable
	SELECT * FROM Candidates WHERE DateWhenCompleteTask IS NULL AND YEAR(DateWhenCompleteTask)>2001
RETURN 0
